name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir production
            cd production
            git clone -b production --single-branch ${{ secrets.REPO_URL }}
            cd ${{ secrets.REPO_NAME }}
            git pull
            chmod +x mvnw
            ./mvnw package
            kill -9 $(lsof -t -i tcp:8080)
            cd target
            nohup java -jar finalProject_synrgy-0.0.1-SNAPSHOT.jar
